### ISSUE TITLE
Fehler 

### ISSUE THREAD

**Issue by m7-sketch** [ValentinSchmitz/spell-checker#1]
Guten Tag, 
ich habe folgendes Problem: 

Fehler

Debuginformationen:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-07-09 20:12:45

Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading", line 980, in _bootstrap_inner
  File "threading", line 917, in run
  File "subprocess", line 1479, in _readerthread
  File "codecs", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 12: invalid start byte
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-5, started daemon 7048)>>
Traceback (most recent call last):
  File "threading", line 937, in _bootstrap
  File "threading", line 982, in _bootstrap_inner
  File "threading", line 1264, in invoke_excepthook
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

Wie löse ich es ? 

Viele Grüße  
M7

**Comment by m7-sketch** [comment]
Hallo Valentin, 
der Fehler ist aufgetreten, als ich das Addon installiert und Anki neu gestartet habe. 

VG 
M7

**Comment by ValentinSchmitz** [comment]
Ich werde mir das nochmal tiefer anschauen müssen, es wird also leider ein bisschen dauern, bis ich eine Lösung parat habe.

**Comment by m7-sketch** [comment]
Dankeschön!

**Comment by JimboJoe** [comment]
Hello,
To let you know, I have the same error with fr or English dictionaries when enabling them (Anki 2.1.66).

**Comment by ValentinSchmitz** [comment]
Hi, can you check if the new version resolved your issue? The plugin should now be compatible with Windows.

**Comment by JimboJoe** [comment]
That works a treat, thank you very much! 👍
